core: add missing include
Not including <sys/sysmacros.h> causes the following error on ARM:

core.c: In function ‘is_gpiochip_cdev’:
core.c:116:4: warning: implicit declaration of function ‘major’ [-Wimplicit-function-declaration]
    major(statbuf.st_rdev), minor(statbuf.st_rdev));
    ^~~~~
core.c:116:28: warning: implicit declaration of function ‘minor’; did you mean ‘mknod’? [-Wimplicit-function-declaration]
    major(statbuf.st_rdev), minor(statbuf.st_rdev));
                            ^~~~~
                            mknod

It wasn't spotted earlier since it builds fine on x86-64. Add the
missing include.

Signed-off-by: Bartosz Golaszewski <bartekgola@gmail.com>